# SPDX-FileCopyrightText: 2025-2026 Vladyslav Melnyk
# SPDX-License-Identifier: GPL-3.0-or-later
# See LICENSE for the full license text.

[toolchain]
components = ["clippy", "rustfmt", "llvm-tools"]
channel = "1.98.1"
targets = ["riscv64imac-unknown-none-elf"]
