"""Import the LPDDR4 register constants from StarFive U-Boot c4c67bb.

Run:
    git clone --rev c4c67bb66ae6f41c98537d18cf5c3abc8b97b8e4 https://github.com/starfive-tech/u-boot.git target/u-boot
    python3 0-M/vf2/tools/import_ddr.py target/u-boot
The generated file is checked in; building Tau does not need U-Boot source.
"""
import re
import subprocess
import sys
from pathlib import Path

root = Path(sys.argv[1]) / 'drivers/ram/starfive'
out = Path(__file__).resolve().parent.parent / 'src/ddr_data.rs'
flags = {'OFFSET_SEL': 1 << 31, 'REG1G': 1 << 30, 'REG2G': 1 << 29,
         'REG4G': 1 << 28, 'REG8G': 1 << 27, 'F_ADDSET': 4,
         'F_SET': 2, 'F_CLRSET': 1, 'REGALL': 15 << 27}
flags['REGSETALL'] = flags['F_SET'] | flags['REGALL']
flags['REGCLRSETALL'] = flags['F_CLRSET'] | flags['REGALL']
flags['REGADDSETALL'] = flags['F_ADDSET'] | flags['REGALL']
arrays = [
    ('ddrphy_train.c', 'lpddr4_train_data', 'u32'),
    ('ddrphy_utils.c', 'lpddr4_phy_data', 'u32'),
    ('ddrphy_start.c', 'lpddr4_start_cfg', 'Cfg'),
    ('ddrcsr_boot.c', 'lpddr4_csr_cfg', 'Cfg'),
    ('ddrcsr_boot.c', 'lpddr4_csr_cfg1', 'Cfg'),
    ('ddrcsr_boot.c', 'ddr_csr_cfg2', 'Cfg'),
    ('ddrcsr_boot.c', 'lpddr4_csr_cfg3', 'Cfg'),
]
text = ['// SPDX-License-Identifier: GPL-2.0+',
        '// Register data imported from starfive-tech/u-boot c4c67bb, drivers/ram/starfive.',
        '// Generated by 0-M/vf2/tools/import_ddr.py. Do not edit by hand.',
        '', '#[derive(Clone, Copy)]',
        'pub(super) struct Cfg { pub offset: u32, pub mask: u32, pub value: u32, pub flags: u32 }',
        '',
]
for file, name, ty in arrays:
    source = (root / file).read_text()
    match = re.search(r'\b' + name + r'\[\]\s*=\s*\{(.*?)\n\};', source, re.DOTALL)
    assert match, (file, name)
    body = re.sub(r'/\*.*?\*/|//[^\n]*', '', match.group(1), flags=re.DOTALL)
    if ty == 'u32':
        vals = [int(v, 0) for v in re.findall(r'0x[0-9a-fA-F]+|\b\d+\b', body)]
        lines = [f'    0x{v:08x},' for v in vals]
    else:
        rows = re.findall(r'\{([^{}]+)\}', body)
        lines = []
        for row in rows:
            parts = [p.strip().strip('()') for p in row.split(',')]
            assert len(parts) == 4, (name, row)
            offset, mask, value = (int(p, 0) for p in parts[:3])
            flag = 0
            for part in parts[3].split('|'):
                flag |= flags[part.strip()]
            lines.append(f'    Cfg {{ offset: 0x{offset:x}, mask: 0x{mask:08x}, value: 0x{value:08x}, flags: 0x{flag:08x} }},')
    text.extend([f'pub(super) static {name.upper()}: [{ty}; {len(lines)}] = [', *lines, '];', ''])
out.write_text('\n'.join(text))
subprocess.run(['rustfmt', str(out)], check=True)
print(out, out.stat().st_size)
